# Generated by Django 2.0.6 on 2020-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
                'db_table': 'bz_teacher',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic/'),
        ),
    ]
